### ISSUE TITLE
error TS2304: Cannot find name 'Promise'

### ISSUE THREAD

**Issue by lopezhansel** [amosgwa/Playing-with-Express#1]
I believe the following error is because were missing some definition files that include 'Promise'
```Error : node_modules/@types/mongodb/index.d.ts(18,64): error TS2304: Cannot find name 'Promise'.```

We tried `npm install -D typings` but that is wrong!  We instead need to do   
```npm install --save-dev @types/core-js```  [check these answers](https://github.com/angular/quickstart/issues/63)

Thats because the `typings` repo migrated into `@types` [more here](http://stackoverflow.com/questions/39261204/typings-vs-types-npm-scope)

**Comment by amosgwa** [comment]
Weird thing is that it wasn't throwing the same error again. I prob forgot how to reproduce it. I remember taking out the Mongodb from the dependencies as well as the @types definition for Mongo.

**Comment by lopezhansel** [comment]
yes we did `npm uninstall mongoose --save` and that go rid of the error temporarily. 
You should be able to us mongoose after doing `npm install --save-dev @types/core-js`  then `npm i mongoose -S`

**Comment by amosgwa** [comment]
Here is your fried chicken as a token of gratitude! I will try to play with db, and make a simple app with express and TypeScript. 💯  

![Fried Chicken](https://cloud.githubusercontent.com/assets/6025663/21116473/f13c9b84-c072-11e6-9e63-a09b8ca46853.jpg)

**Comment by lopezhansel** [comment]
Thank you Juan! Good Luck!
